DROP TABLE IF EXISTS favourite CASCADE;

CREATE TABLE favourite (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  listing_id VARCHAR(255) NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
);
