DROP TABLE IF EXISTS listings CASCADE;

CREATE TABLE listings (
  id SERIAL PRIMARY KEY NOT NULL,
  image_id INTEGER NOT NULL REFERENCES images(id) ON DELETE CASCADE,
  text VARCHAR(255) NOT NULL,
  price INTEGER NOT NULL,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  featured BOOLEAN NOT NULL DEFAULT FALSE,
  sold BOOLEAN NOT NULL DEFAULT FALSE,
  date_added DATE NOT NULL
);
